### PR TITLE
Add support for multiple M3Us/EPGs via instances - Nexus

### PR DESCRIPTION
**Pull request by phunkyfish**
v20.8.0
- Add support for multiple instances each supporting their own M3U/XMLTV and settings

### CODE REVIEW

**Comment by phunkyfish** [comment]
@howie-f could you try building and installing this. I'm having an issue (just with this add-on, not pvr.vuplus or pvr.vbox) where it's crashing when the add-on is disabled.

It will crash after the log statement: `ADDON: Dll Destroyed - IPTV Simple Client`. The annoying this is that the debugger does not catch the crash so I can't backtrace it:

```
Process 24554 stopped
* thread #28, stop reason = EXC_BAD_ACCESS (code=1, address=0x12636c45a)
    frame #0: 0x000000012636c45a
error: memory read failed for 0x12636c400
Target 0: (kodi.bin) stopped.
(lldb) thread backtrace
* thread #28, stop reason = EXC_BAD_ACCESS (code=1, address=0x12636c45a)
  * frame #0: 0x000000012636c45a
```

**Comment by phunkyfish** [comment]
Ok, my debugger finally caught one of the crashes. @AlwinEsch FYI

```
2023-02-11 21:42:56.365354+0000 kodi.bin[36086:388351] 2023-02-11 21:42:56.365 T:388351    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEPG - EPG file path is not configured. EPG not loaded.
2023-02-11 21:42:56.365430+0000 kodi.bin[36086:388351] 2023-02-11 21:42:56.365 T:388351    info <general>: AddOnLog: pvr.iptvsimple: Initialise Starting separate client update thread...
2023-02-11 21:42:56.431109+0000 kodi.bin[36086:388351] 2023-02-11 21:42:56.431 T:388351    info <general>: PVR Manager: Starting
2023-02-11 21:42:56.494257+0000 kodi.bin[36086:388371] 2023-02-11 21:42:56.494 T:388371    info <general>: PVR Manager: Started
2023-02-11 21:43:02.787275+0000 kodi.bin[36086:388089] 2023-02-11 21:43:02.787 T:388089    info <general>: Loading skin file: AddonBrowser.xml, load type: KEEP_IN_MEMORY
2023-02-11 21:43:08.233140+0000 kodi.bin[36086:388089] 2023-02-11 21:43:08.232 T:388089    info <general>: Loading skin file: DialogAddonInfo.xml, load type: KEEP_IN_MEMORY
2023-02-11 21:43:10.818340+0000 kodi.bin[36086:388089] 2023-02-11 21:43:10.818 T:388089    info <general>: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY
2023-02-11 21:43:13.379216+0000 kodi.bin[36086:388351] 2023-02-11 21:43:13.379 T:388351    info <general>: PVR Manager: Stopping
2023-02-11 21:43:13.562204+0000 kodi.bin[36086:388378] 2023-02-11 21:43:13.562 T:388378    info <general>: EPG Container: Persisting unsaved events...
2023-02-11 21:43:13.562929+0000 kodi.bin[36086:388378] 2023-02-11 21:43:13.562 T:388378    info <general>: EPG Container: Persisting events done
Process 36086 stopped
* thread #34, name = 'JobWorker', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x0000000100afb04c kodi.bin`CJobManager::OnJobComplete(this=0x000000010ff634b8, success=true, job=0x0000600000d1d7a0) at JobManager.cpp:410:26
   407 	    try
   408 	    {
   409 	      if (item.m_callback)
-> 410 	        item.m_callback->OnJobComplete(item.m_id, success, item.m_job);
   411 	    }
   412 	    catch (...)
   413 	    {
Target 0: (kodi.bin) stopped.
(lldb) thread backtrace
* thread #34, name = 'JobWorker', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x0000000100afb04c kodi.bin`CJobManager::OnJobComplete(this=0x000000010ff634b8, success=true, job=0x0000600000d1d7a0) at JobManager.cpp:410:26
    frame #1: 0x0000000100afad35 kodi.bin`CJobWorker::Process(this=0x000000011018bc20) at JobManager.cpp:61:19
    frame #2: 0x0000000100c2f7c4 kodi.bin`CThread::Action(this=0x000000011018bc20) at Thread.cpp:267:5
    frame #3: 0x0000000100c35b6c kodi.bin`CThread::Create(this=0x000060000032d560, pThread=0x000000011018bc20, promise=promise<bool> @ 0x00007000043cdf20)::$_0::operator()(CThread*, std::__1::promise<bool>) const at Thread.cpp:138:18
    frame #4: 0x0000000100c35879 kodi.bin`decltype(__f=0x000060000032d560, __args=0x000060000032d568, __args=0x000060000032d570)::$_0>(fp)(static_cast<CThread*>(fp0), static_cast<std::__1::promise<bool>>(fp0))) std::__1::__invoke<CThread::Create(bool)::$_0, CThread*, std::__1::promise<bool> >(CThread::Create(bool)::$_0&&, CThread*&&, std::__1::promise<bool>&&) at type_traits:3918:1
    frame #5: 0x0000000100c357e7 kodi.bin`void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CThread::Create(bool)::$_0, CThread*, std::__1::promise<bool>, 2ul, 3ul>(__t=size=4, (null)=__tuple_indices<2, 3> @ 0x00007000043cdf68)::$_0, CThread*, std::__1::promise<bool> >&, std::__1::__tuple_indices<2ul, 3ul>) at thread:287:5
    frame #6: 0x0000000100c34ee2 kodi.bin`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CThread::Create(bool)::$_0, CThread*, std::__1::promise<bool> > >(__vp=0x000060000032d560) at thread:298:5
    frame #7: 0x00007ff8132ae259 libsystem_pthread.dylib`_pthread_start + 125
    frame #8: 0x00007ff8132a9c7b libsystem_pthread.dylib`thread_start + 15
```

**Comment by howie-f** [comment]
sorry, the failure with two instances persists with https://github.com/kodi-pvr/pvr.iptvsimple/pull/699/commits/8e36327da9afbc16b72638230493c31117cf2259
```
2023-02-12 13:34:15.650 T:31338   error <general>: IAddonInstanceHandler::CreateInstance: pvr.iptvsimple returned bad status "Permanent failure" during instance creation
2023-02-12 13:34:15.651 T:31338   error <general>: UpdateClients: Failed to create add-on pvr.iptvsimple, status = 5
```

**Comment by phunkyfish** [comment]
Latest commits work correctly, tested on both Mac and Linux.

**Review by howie-f — APPROVED** [review]

**Comment by DrSpaldo** [comment]
If I am running Kodi on Nvidia Shield, would it be possible to try out this version? I would like to have multiple instances of NextPVR

**Pull request merged**
