### PR TITLE
Bump add-on (libplatform dependency)

### PR DESCRIPTION
**Pull request by hudokkow**

### CODE REVIEW

**Comment by afedchin** [comment]
I don't understand this. Just bump version to fix platform dependency?

**Comment by hudokkow** [comment]
Yes, statically linked against libplatform

**Comment by Jalle19** [comment]
@afedchin without bumping the version number Kodi won't update the addon.

**Comment by afedchin** [comment]
perhaps this is a linux specific thing. As I know pvr addons distributed with Kodi together.

**Comment by afedchin** [comment]
sorry for noise

**Pull request merged**
