### PR TITLE
Timeshift matrix

### PR DESCRIPTION
**Pull request by phunkyfish**
v4.1.0

- Added: Support for Timeshifting

### CODE REVIEW

**Comment by Sorien** [comment]
I'd like to point out to special use-case of iptvsimple. I have plugin that is using iptvsimple to play DRM protected streams, M3u playlist is created by python plugin service with links like 
```
#EXTINF:-1 tvg-id="123456" tvg-logo="channel.png",channel 7
plugin://plugin.video.sl/?action=play&id=...&askpin=False
```
these links are callbacks to plugin that is resolving them and then are played with inputstreamadaptive.

I'm not sure if it can be timeshifted, probably not, so it would be nice to have some kodi prop in m3u file to disable timeshift for certain streams.

**Comment by phunkyfish** [comment]
This PR won’t to be added to iptvsimple, there are other pvr addons available to do timeshift on IPTV. It was a pet project for me to see if I could get it to work.

**Comment by AlwinEsch** [comment]
Related to https://github.com/xbmc/xbmc/pull/17307, not forget a rebase of request to allow further Jenkins use!

```sh
git remote add upstream https://github.com/kodi-pvr/pvr.iptvsimple
git fetch upstream
git rebase upstream/Matrix
```

**Comment by phunkyfish** [comment]
Ah, I may just need to manually update/cherry pick the change. The branch is quite old.

**Comment by phunkyfish** [comment]
Closing, timeshift feature released on Matrix using inputstream.ffmpegdirect.

**Pull request closed without merging**
