### PR TITLE
Increase Line Length to standard 4k

### PR DESCRIPTION
**Pull request by Shani-08**
Some of the Urls with ,ore than 1000 characters are being ignored. redoing this PR as the other one had multiple commits.

### CODE REVIEW

**Comment by Jalle19** [comment]
Can you update the changelog and bump the addon version number too?

**Comment by Jalle19** [comment]
Thanks!

**Comment by Jalle19** [comment]
@Shani-08 would you mind doing a similar PR for the Krypton branch?

**Comment by Shani-08** [comment]
sure

**Pull request merged**
