### PR TITLE
added: pass on kodi properties from m3u

### PR DESCRIPTION
**Pull request by notspiff**
in particular this allows for inputstream.adaptive streams (dash etc)

@ksooo @peak3d

### CODE REVIEW

**Comment by notspiff** [comment]
added the bump.

**Comment by ksooo** [comment]
Thanks, it would be nice if you update https://github.com/kodi-pvr/pvr.iptvsimple/blob/master/pvr.iptvsimple/changelog.txt as well.

**Comment by notspiff** [comment]
and the changelog.

**Comment by ksooo** [comment]
Thansk @notspiff

**Pull request merged**
