### PR TITLE
DST Fix (Leia)

### PR DESCRIPTION
**Pull request by matthuisman**
This is @buers code.
He is unfamiliar with git so I am making a pull request on his behalf.

Issue with discussion here:
https://github.com/kodi-pvr/pvr.iptvsimple/issues/158

### CODE REVIEW

**Comment by matthuisman** [comment]
Test builds here:
https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-249/1/artifacts

**Comment by buers** [comment]
Thanks. Unfortunately, I fear I cannot test the builds immediately, because I only have Krypton installed. Can it be backported there too? I am happy, to have a look, if somebody helps to give me the correct link to the source.

Whoever is wanting to test it: On non-Windows plattforms, you shouldn't see any difference at the moment. When approaching the next DST-Change (here it will be in October), and current time is still before the DST-change, but you view EPG-data from after the DST-change, it should show correct time (formerly it was one hour off). I fear a good test is not very easy to set up. (Manipulate current time and also create some artifical xmltv-EPG data).

On Windows-Platform, when your timezone currently has DST (typically in the Northern hemisphere at the moment) probably EPG times will be displayed one hour off in Kodi at the moment. The branched version should show correct times.

**Comment by matthuisman** [comment]
I'm making up a test.xml and test playlist.
image

This will be for NZ's last DST change 7th April 2019 3:00am.

**Comment by matthuisman** [comment]
@buers
I tested in windows, and it seems I still need to restart kodi so the EPG reloads.
Then the times are correct.

Still it fixes the need to adjust the offset that is currently required.

@buers
I did a pull request for Krypton but travis no longer builds for it (as it's old version now)
So removed that pull request

**Review by Sorien — APPROVED** [review]
I tested it with my addon and it's working like expected (Kodi Leia 18.1 64bit - Windows 10)

**Comment by matthuisman** [comment]
new test builds:
https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-249/2/artifacts

**Comment by matthuisman** [comment]
Latest builds:
https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-249/3/artifacts

**Comment by ksooo** [comment]
No need to publish the link for every new build. Meanwhile, people should know where to find. Remember, every posting here triggers notifications for many people. As an example, I get up to  100 github notifications a day. So, please avoid noise for  no real reason.

**Comment by ksooo** [comment]
Superseded  by #257

**Pull request closed without merging**
