### PR TITLE
Matrix [Fix Typo]

### PR DESCRIPTION
**Pull request by I-Cat**
Ok Looks Good.

### CODE REVIEW

**Review by I-Cat — COMMENTED** [review]
yey

**Comment by phunkyfish** [comment]
This PR needs to be a single commit. There is no reason to have 6 commits to change one typo.

Also, there is no point in reviewing your own PR. Someone else needs to review it that is not you.

**Comment by I-Cat** [comment]
Okay. n.p off to the cmd I go

**Comment by I-Cat** [comment]
@phunkyfish I Can't start a new pull request It says its locked?
thank you

**Pull request closed without merging**
