### PR TITLE
[lang] Update language for zh_cn

### PR DESCRIPTION
**Pull request by Meano**
Update zh_cn language file for pvr.iptvsimple.

### CODE REVIEW

**Comment by phunkyfish** [comment]
Only the en_gb file can be update here. All other languages are auto translated by transifix.

**Comment by Meano** [comment]
> Only the en_gb file can be update here. All other languages are auto translated by transifix.

Oh, there's no access permission in transifex KODI Main project, and nobody reply the language request...

**Comment by phunkyfish** [comment]
Let me ask.

**Comment by phunkyfish** [comment]
We are migrating to a new translation tool. So unless someone picks up the language request it will have to wait until the migration is completed. Check back on this thread in a few weeks and I’ll see what progress we have.

**Comment by Meano** [comment]
OK, thanks a lot!

**Comment by Meano** [comment]
I'm updating the translation on weblate, this PR is not needed anymore.

**Pull request closed without merging**
