### PR TITLE
[Fix spelling and do proper pull request] File: Updated = Rytec-UK-Ireland.xml

### PR DESCRIPTION
**Pull request by I-Cat**
[Fix spelling and do proper pull request] File: Updated = Rytec-UK-Ireland.xml

yippy!
Don't know why It was giving me a hard time to fix this .

### CODE REVIEW

**Comment by I-Cat** [comment]
Mention @phunkyfish

**Comment by AlwinEsch** [comment]
As note to git by previous request, there can be leaved on same request and branch. Already present code can be still on opened pull request changed.

E.g. about other request:
```
git reset --soft HEAD~6 # The reset with --soft not change the code only the related commits are unset, HEAD means uppest place and ~6 how many commits it should go back
git commit -m "Update Rytec-UK-Ireland.xml"
git push -f # The -f force to change existing code inside a branch
```

**Comment by AlwinEsch** [comment]
To compare at home before a request is opened:
```
git remote add upstream https://github.com/kodi-pvr/pvr.iptvsimple
git fetch upstream
git format-patch upstream/Matrix # upstream to mark for other place and Matrix the wanted branch there
```
Name upstream can also another e.g. myotherplacename, is only a value name about URL

The `git format-patch` write then all commits to separate files and how they are then come on request.

**Review by phunkyfish — APPROVED** [review]
Thanks for the contribution

**Comment by I-Cat** [comment]
@AlwinEsch 
@phunkyfish 

Thanks for helping!
😄

**Pull request merged**
