### PR TITLE
Allow jenkins to build on any branch for testing, Add appveyor to build. [Thanks]

### PR DESCRIPTION
**Pull request by I-Cat**
Allow jenkins to build on any branch for testing, Add appveyor to be a builder.
For Me I cannot log in to [https://dev.azure.com/teamkodi/kodi-pvr/_apis/build/status/kodi-pvr.pvr.iptvsimple?branchName="branch"]. By being a ristricted access I & others won't beable to see the azure/Windows biuld flow.
Also can You please update the "Readme.md" to include the azure/Windows build flow please. Thank you.

### CODE REVIEW

**Comment by phunkyfish** [comment]
Appveyor is no longer used for binary addons.

**Comment by I-Cat** [comment]
@phunkyfish Oh Okay. I didn't Know that. Can you tell/help me to do it the proper way to build Kodi, So that I Can Learn How to Build kodi the correct way. With the correct binary.

**Comment by phunkyfish** [comment]
Windows builds are created by Jenkins when you create a PR. Just click the Jenkins check, and from the CI page click artifacts.

Or do you mean to build the addon locally?

**Comment by I-Cat** [comment]
@phunkyfish To build localy, So I can start fixing issues. Sometimes a local build is better because a tweek ect can be done without a rebuild every time.

**Comment by phunkyfish** [comment]
If you want to build the addon locally you should first set up your machine to build kodi. Once you can build kodi you know you have the pre-requisites to build an addon.

**Comment by I-Cat** [comment]
Okay. Thanks for the responces.

**Pull request closed without merging**
