### PR TITLE
[depends] rapidxml: split windows from common

### PR DESCRIPTION
**Pull request by Rechi**

### CODE REVIEW

**Comment by phunkyfish** [comment]
Would be great to get this approved.

**Review by phunkyfish — APPROVED** [review]
I've pullled this locally and it works as expected

**Comment by phunkyfish** [comment]
@ksooo, @afedchin this works, can it be merged?

**Comment by phunkyfish** [comment]
Can this be merged?

**Comment by kyl416** [comment]
Can we please get this merged? This is preventing other pull requests from passing the checks.

**Pull request merged**
