### PR TITLE
Remove channels loaded notification

### LINKED ISSUE #222: Request: Please add option to disable notification pop on Kodi start-up
Small request just to add an option in settings to disable the notification msg, that is all :)

### PR DESCRIPTION
**Pull request by allixx**
resolves #222

### CODE REVIEW

**Comment by ksooo** [comment]
Just drop that silly popup; no setting needed.

**Review by ksooo — APPROVED** [review]

**Comment by ksooo** [comment]
Could you please bump the addon micro version number and update the change log.

https://github.com/kodi-pvr/pvr.iptvsimple/blob/Matrix/pvr.iptvsimple/changelog.txt
https://github.com/kodi-pvr/pvr.iptvsimple/blob/Matrix/pvr.iptvsimple/addon.xml.in

**Comment by allixx** [comment]
Hmm i'm not sure what happened here, should I reopen pull request?
https://github.com/allixx/pvr.iptvsimple/commit/386a885b39778f7745b4ee27c99209df4ce2fe72

**Comment by ksooo** [comment]
Afaict, all fine.. Thanks.

**Pull request merged**
