### PR TITLE
[Leia] update CMakeLists.txt to 3.5, change header include and increase version to 3.7.2

### PR DESCRIPTION
**Pull request by AlwinEsch**

### CODE REVIEW

**Comment by phunkyfish** [comment]
Can you also add appveyor to the readme?

**Comment by phunkyfish** [comment]
This ok to go in now @AlwinEsch ?

**Review by phunkyfish — APPROVED** [review]

**Comment by AlwinEsch** [comment]
Yes, both can in.

**Comment by AlwinEsch** [comment]
Wait a second the appveyor file not present

**Comment by phunkyfish** [comment]
It's already there. Added as part of PR yesterday.

**Pull request merged**
