### PR TITLE
Catchup type m3u

### PR DESCRIPTION
**Pull request by phunkyfish**
v5.1.0
- Added: Support catchup-type M3U property
- Added: Set MIME type and manifest on stream types if required
- Added: Support multiple occurrences of year, month and day in catchup format specifiers
- Update: Change docs to use inputstream instead of inputstreamclass

### CODE REVIEW

**Comment by SerhiyRomanov** [comment]
@phunkyfish I've tried to install the addon from this pull, but get errors:

```
2020-05-22 12:12:28.097 T:177127   ERROR <general>: Add-on 'inputstream.rtmp' is not compatible with Kodi
2020-05-22 12:12:28.097 T:177127   ERROR <general>: CAddonInstallJob[pvr.iptvsimple]: The dependency on kodi.binary.global.main version 1.1.0 could not be satisfied.
```

My Kodi version:
```
2020-05-22 12:12:12.520 T:177115    INFO <general>: Starting Kodi (19.0-ALPHA1 Git:20200521-12d19656a8). Platform: Linux x86 64-bit
2020-05-22 12:12:12.520 T:177115    INFO <general>: Using Release Kodi x64 build
2020-05-22 12:12:12.520 T:177115    INFO <general>: Kodi compiled 2020-05-21 by GCC 9.3.0 for Linux x86 64-bit version 5.4.34 (328738)
2020-05-22 12:12:12.520 T:177115    INFO <general>: Running on Ubuntu 20.04 LTS, kernel: Linux x86 64-bit version 5.4.0-31-generic
2020-05-22 12:12:12.520 T:177115    INFO <general>: FFmpeg version/source: 4.2.2-Kodi
```

**Comment by phunkyfish** [comment]
You will need the latest kodi version which you appear to have which is strange.

**Comment by phunkyfish** [comment]
Did you build the addon against the same version of kodi?

**Comment by phunkyfish** [comment]
`kodi.binary.global.main` was switched to `1.2.0` On May 17th.

I think the source you kodi was built from is a bit older than that.

See here: https://github.com/xbmc/xbmc/commits/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/versions.h

**Comment by SerhiyRomanov** [comment]
@phunkyfish I use Kodi from Kodi Nightly Builds Ubuntu repo 
https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly?field.series_filter=focal
By the way, despite the latest kodi-pvr-iptvsimple	5.0.0-1 ~ focal seems like available on the repo, I am still getting 4.14.2-1 ~ focal version when trying to install it from the repo. 

19.0-ALPHA1 Git:20200521-12d19656a8 - seems like my build based on actual master, the latest commit is https://github.com/xbmc/xbmc/commit/12d19656a813d2c798c1933f548cfc32232d06b6
So, it's strange.

**Comment by phunkyfish** [comment]
It would appear those nightly builds are incorrect somehow because 5.0.0 of the addon also require 1.2.0 of global main. (Hence the bump to 5.x)

**Comment by phunkyfish** [comment]
@wspinex, since binary addons changed the global main version is there anything special required for Ubuntu builds that we missed?

They appear to be tied to the previous version.

**Comment by SerhiyRomanov** [comment]
Any updates?

**Comment by phunkyfish** [comment]
@wsnipex and I incorrectly typed your username, which is why you have had no idea what I was talking about on slack.

**Comment by phunkyfish** [comment]
@SerhiyRomanov it looks like the fix for this will be to merge the PR. I will do that once the Jenkins is happy. If there are any issues let me know.

**Pull request merged**
