### PR TITLE
source pvr.hts -> pvr.iptvsimple

### PR DESCRIPTION
**Pull request by howie-f**
@phunkyfish

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
Thanks, could you do the same for the Matrix branch?

**Comment by howie-f** [comment]
sure there it is https://github.com/kodi-pvr/pvr.iptvsimple/pull/583

**Comment by phunkyfish** [comment]
Thanks!

**Comment by ksooo** [comment]
Nice find.

**Comment by howie-f** [comment]
karellen‘s find… 🥇 i‘m just the executive assistant

**Pull request merged**
