### PR TITLE
fix epg performance

### PR DESCRIPTION
**Pull request by phunkyfish**
v4.11.4
- Fixed: EPG performance
- Update: PVR API 6.3.0
- Added: GPLv2+ badge on README

### CODE REVIEW

**Comment by phunkyfish** [comment]
@SerhiyRomanov ^^^

Can you test this? Needs some runtime testing to see if it helps.

**Comment by SerhiyRomanov** [comment]
@phunkyfish 
I use Kodi nightly build (2:19.0+git20200302.0308-fc48d57403-0bionic) and got this error when trying to install the compiled addon from this PR 
`2020-03-20 12:33:29.780 T:14235   ERROR: CAddonInstallJob[pvr.iptvsimple]: The dependency on kodi.binary.instance.pvr 6.2.0 could not be satisfied.`

What should I do?

**Comment by phunkyfish** [comment]
Your nightly is not new enough. The PVR API changed a few days ago.

You need one from after the 17th March

**Comment by SerhiyRomanov** [comment]
@phunkyfish 
I got new builds from APT repo for Ubuntu. 

```
2020-03-27 11:06:57.398 T:30834  NOTICE: Starting Kodi (19.0-ALPHA1 Git:20200327-e1d4e5ecc5). Platform: Linux x86 64-bit
2020-03-27 11:06:58.052 T:30834  NOTICE: CAddonMgr::FindAddons: kodi.binary.instance.pvr v6.3.0 installed
2020-03-27 11:07:17.480 T:30918  NOTICE: CAddonMgr::FindAddons: pvr.iptvsimple v4.11.4 installed
```
But still get the error that
```
2020-03-27 11:09:32.537 T:30834   ERROR: Add-on 'pvr.iptvsimple' is not compatible with Kodi
```

**Comment by phunkyfish** [comment]
Because there was another API update yesterday. But they are done now so once you get one from 2020-03-27 or later you should be ok!

**Comment by phunkyfish** [comment]
hmm. Wait that should be correct. 4.11.4 for the addon abs 6.3.0 for API should be right.

**Comment by SerhiyRomanov** [comment]
@phunkyfish Yes, I thought that should works. I've re-installed Kodi and Addon from repo but still don't work(

**Comment by phunkyfish** [comment]
Let me do a test locally.

**Pull request merged**
